### ISSUE TITLE
Selection with rowid

### ISSUE THREAD

**Issue by ARF1** [ContinuumIO/blaze#962]
Many backends use an inherent rowid (sqlite, bcolz). Having access to the internal rowid of the backend would be very useful for modifying rows in the database.

Pseudo use case with bcolz:
```
db = bcolz.open(rootdir='../my_db', mode='a')
d = blaze.Data(db)

a = d[['nrow__', 'col1', 'col2']]
b = a[(a.col1 == a.col2)]
c = b[['nrow__']]
d = blaze.compute(c)

db['col3'][d] = 'col1 and col2 are identical'
```

Currently using the bcolz special column name `nrow__` produces the error message:
```
ValueError: Names ['nrow__', 'col1', 'col2'] not consistent with known names ['col1', 'col2', 'col3']
```
I imagine for other backends similar issues arise.

A simple solution would be to add the rowid "special column name" automatically to the list of column names for each backend. E.e. `ROWID` for sqlite, `nrow__` for bcolz...

A nicer solution would be to provide an abstaction layer for the name of the rowid column in blaze to make code using rowid more portable. This is not really a priority since blaze does not (yet?) provide writing to backends which would be the primary application imho and backend-specific code would thus be required anyway...

**Comment by cpcloud** [comment]
This going to be backend specific. With SQL it's even more complicated because of the vendor specific differences. If a particular backend implements the `Slice` expression then this functionality is accessible. I don't think we'll be implementing this any time soon for all backends. Pull requests are welcome here. Closing for now.
